* Estrutura de diretórios

<nome_do_preditor>/
<nome_do_preditor>/cnf/meta.cnf
<nome_do_preditor>/submodels
<nome_do_preditor>/submodels/cnf/arquivos.cnf
<nome_do_preditor>/submodels/model.0/
<nome_do_preditor>/submodels/model.1/
<nome_do_preditor>/submodels/model.2/
<nome_do_preditor>/submodels/model.3/
<nome_do_preditor>/ghmm/ghmm_geometric_intron.model
<nome_do_preditor>/ghmm/ghmm_intron_short.model
<nome_do_preditor>/ghmm/ghmm_single_gene.model
<nome_do_preditor>/scripts/ghmm_intron_short.pl
<nome_do_preditor>/scripts/ghmm_geometric_intron.pl
<nome_do_preditor>/scripts/ghmm_without_isochore.pl


* Formato do meta.cnf

O arquivo serve para armazenar os metaparâmetros.  Para criar novo
metaparametros basta adicionar ele aqui.

start_length = 20
start_offset = 20
introduçãon_short_length = 584
intergenic_length = 1e4
stop_codon_length = 3
stop_codon_offset = 0
acceptor_length=6
start_initial_pattern_length = 4
acceptor_initial_pattern_length = 3
acceptor_offset=3
donor_length=9
donor_offset=3
branch_length=32
isochore_max = 0.60
isochore_min = 0.30
isochore_nband = 5

* Scripts que preciso

** DONE myop-train.pl -r <repositorio do modelo> [ -b <nome do modelo> ] -g <arquivo.gtf> -f <arquivo.fasta> -a <cpu> -o <diretorio de saida>
*** atualize o train.gtf e o train.fa, verifique se há erros de anotação.
*** criar diretorio dataset
*** criar diretorio ghmm/cnf
*** criar diretorio ghmm/dataset
*** executa o myop-setup.pl
*** executa o myop-generate_training_set.pl
*** executa o myop-train_submodels.pl
*** executa o myop-build_ghmm.pl

** DONE myop-setup.pl
*** DONE para cada arquivo cnf, entrar e substituir os metaparametros apenas se a data do cnf for anterior a data do meta.cnf.

** DONE myop-generate_training_set.pl
*** DONE para cada arquivo cnf,  executar o comando que esta no parametro myop_extract_dataset_script.

** DONE myop-train_submodels.pl
*** para cada arquivo cnf, executar o comando que esta no parametro myop_training_algorithm
*** se for isochore dependente, repetir o processo para cada band

** DONE myop-build_ghmm.pl
*** executar cada script em build_ghmmb_scripts


** TODO myop-predict.pl -d <diretorio do modelo> -l
*** lista os modelos ghmm disponiveis para a decodificacao

** TODO myop-predict.pl -d <diretorio do modelo> -f <arquivo fasta> -a <numero de cpu> -o <diretorio de saida>
*** quebrar o arquivo fasta em pedaços menores
result/genes.gtf
result/cds.fa
result/cds.pep


* Uso pelo usuario...

myop_train.pl -r http://www.vision.ime.usp.br/~yoshiaki/myop_templates/  -g hsapiens.gtf -f hsapiens.fa -c 5 -o hsapiens
myop_predict.pl -d hsapiens -a 4 -f test.fa -o result_test/



